### ISSUE TITLE
Show better error message when wallet descriptor changes 

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-cli#11]
If the `bdk-cli` command is used with an existing database but given a new descriptor an error like this is returned: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ChecksumMismatch', /Users/td/.cargo/registry/src/github.com-1ecc6299db9ec823/bdk-cli-0.1.0/src/bdk_cli.rs:119:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
A more informative message should be given so the user knows they can fix the problem by using a different wallet name or removing the existing `~/.bdk-bitcoin` directory.

**Comment by notmandatory** [comment]
Another way to handle this might be to remove wallet name as an option, and just use the descriptor checksum as the DB tree name. Then we should never get this error and the `bdk-cli` tool can be used easily with multiple descriptors data cached in the same database.

**Comment by thunderbiscuit** [comment]
I like the idea of being explicit. If this error had not happened to me and bdk simply made a new wallet for each new test I made I would not have known really what happened to all my descriptors/wallets/tests.

A good idea might be to print a message for the user whenever a brand new wallet is created:
```sh
New wallet 'main' created at ~/.bdk-bitcoin`
```
or something like that, making it really explicit and obvious that bdk is keeping track of it, it's in this database, and it has a name. Just spitballing here.

**Comment by notmandatory** [comment]
Adding a notice when a new wallet is added is a good idea. 

As for wallet names, I was thinking of not using names because the db is only really a cache of wallet data that can always be regenerated from the descriptor, I'm not sure if there's ever a reason to choose a wallet name. Essentially each descriptor gets it's own cache of blockchain data, the cli just allows you to give the cached data for a descriptor a wallet name, but if you use a wallet name for a different descriptor you're always going to get an error, so may better to just auto generate the name from the descriptor. We need to see if we can think of a use case for naming the cashed wallet data.

**Comment by thunderbiscuit** [comment]
Yeah good point.

I was playing with it this morning and was wondering if maybe the wallet names could be used to shorten the commands and skip providing the descriptor? It's not really that necessary but I was writing notes for myself and thought maybe that was actually already the case. Say for example:

```
bdk-cli --wallet "testwalletnumber1" --descriptor "wpkh(tprv8ZgxMBicQKsPdTayefG3Up8B1Rq3AwqQDfvEjt6oJCCwse3s79er2hYn8erb4rTgddL55SGKa8TjkoytzZXc7Kj4BLZwu2rzCFbE1KMfQtF/84'/1'/0'/0/*)" sync
```

Upon further use of the wallet what if you could do:
```
bdk-cli --wallet "testwalletnumber1" get_new_address
```
Skipping the descriptor?

**Comment by thunderbiscuit** [comment]
Mmmm. Now that I'm reading myself I see that this is basically just rebuilding the repl... not too groundbreaking.

**Comment by notmandatory** [comment]
The main point is that the cli doesn't save any descriptor info in the DB, only a cache of block/transaction data. At least for now key/descriptor storage is meant to be left to the user.

**Comment by thunderbiscuit** [comment]
Ah yes of course.

**Comment by notmandatory** [comment]
Better error now provided via #23, resolves this issue.

New checksum error looks like this:
```
[2021-03-15T19:51:31Z ERROR bdk_cli] Descriptor checksum mismatch. Are you using a different descriptor for an already defined wallet name? (if you are not specifying the wallet name it defaults to 'main')
```
