### ISSUE TITLE
Add a sub-command to compile a miniscript policy into a descriptor

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-cli#20]
Given a miniscript spending "policy" and an optional script type ("sh", "wsh", or "sh-wsh") with default "wsh", compile the policy into it's corresponding output descriptor. 

This is a command we found would be handy to have while creating the ["Spending Policy Demo"] blog post.

["Spending Policy Demo"]: https://bitcoindevkit.org/blog/2021/02/spending-policy-demo/

**Comment by afilini** [comment]
Fixed by #21
