### ISSUE TITLE
Enforce build toolchain?

### ISSUE THREAD

**Issue by RCasatta** [bitcoindevkit/bdk-cli#27]
Electrs enforce build with a specific toolchain, which is good practice for binary projects as explained in the commit
https://github.com/romanz/electrs/commit/3c4cf729600e94f83ee3104adf797306e10f77ba

we may want to consider to do the same

**Comment by notmandatory** [comment]
This looks like a good idea. As something related to this issue I think we should also take `Cargo.lock` out of `.gitignore` and commit that file in our repo, per [recommendation in FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).

**Comment by DarthBenro008** [comment]
I'd like to take this up and add it in CI as well has commit the `Cargo.lock` file. Should we set the rust-toolchain to version `1.53.0`?

**Comment by notmandatory** [comment]
Great! yes please use the `1.53.0` rust-toolchain since it's the current stable version.
