### ISSUE TITLE
Feature request: address index in verbose output

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-cli#40]
Would love to be able to tell the address index on the `get_new_address` method if a verbose flag was enabled!

**Comment by notmandatory** [comment]
:+1: good idea

**Comment by thunderbiscuit** [comment]
I wonder if this might be a good issue for @mbcse to try and tackle. Is that something you'd be interested in Mohit?

**Comment by mbcse** [comment]
> I wonder if this might be a good issue for @mbcse to try and tackle. Is that something you'd be interested in Mohit?

Sure will try this out!

**Comment by mbcse** [comment]
I found out that we can use fetch_index function to get the current index but it seems that function is private in the bdk, should I go for bdk level change?

P.S: Although I am still finding other possibilities to do this

**Comment by notmandatory** [comment]
My suggestion is to make the `AddressInfo` struct in `bdk` serializable with the derive macro:
```
#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct AddressInfo { 
... etc
```

Then in `bdk-cli` for the GetNewAddress command return the whole AddressInfo struct instead of only the AddressInfo.address value.

**Comment by rajarshimaitra** [comment]
Hey @mbcse , are you still working on this?

**Comment by rajarshimaitra** [comment]
@mbcse if you are short on time for this one, I am taking it up.. Let me know if you already have made progression..
