### ISSUE TITLE
Create Integration tests for bdk-cli

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk-cli#62]
After Proof of Reserves capability is merged in https://github.com/bitcoindevkit/bdk/commit/b2ac4a0dfd33e1286059d0bd090fd9137e2545ba, its time we require some integration tests in the library. Not only for Proof of Reserves functionality, but in general wallet functions too.

This then can be added into CI tests to give us better reliability on the underlying bdk functions.

[electrsd](https://github.com/RCasatta/electrsd) can be used similarly to the bdk test framework to simulate a electrum and bitcoin core backend. https://github.com/bitcoindevkit/bdk/blob/64e88f0e006c68315142d53dc35b633327dde4b5/src/testutils/blockchain_tests.rs#L19-L22

**Comment by notmandatory** [comment]
I'm going to merge #89 and #71 for 0.5.0 and then I think we should release it. Can we move this issue to next milestone 0.6.0?

**Comment by rajarshimaitra** [comment]
Yes I also feel we should release the current bunch before that change, and push this to next release.. Because that PR will have some upstream pendings.. 

 - `electrsd` - Waiting for https://github.com/RCasatta/bitcoind/pull/61 and a new `electrsd` release.
 
- `bdk v0.190` (maybe?) - To include `bitcoincore-rpc v0.15.0` which is dependency of latest `electrsd` . Which I saw Alekos already did in the taproot PR. Without that the code will have compile time conflict because it uses `bitcoincore-rpc` from two different crates.. `bdk v0.18.0` will have dependency conflict with the PR. We can probably work around it in cargo with patches until `bitcoincore-rpc v0.15.0` gets into bdk in next release. 

I will open the PR shortly though with those temporary fixes, so we can discuss over the node communication approach and improving the test framework..
