### ISSUE TITLE
Add optional features for wallet data

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-cli#63]
Currently `bdk-cli` can only use the `bdk/key-value-db` feature for wallet data storage. I propose we make the `bdk/default` memory database the default for `bdk-cli`, and add two new optional and mutually exclusive features that enable use of the `bdk/key-value-db` or `sqlite` DBs which override using the memory DB. These features could be named `key-value-db` and `sqlite`. 

The purpose of this requested change is to make it possible to test `bdk` using the `bdk-cli` tool with any of the three possible wallet data storage options.

**Comment by notmandatory** [comment]
EDIT: If possible I'd like to make the database features NOT mutually exclusive.

**Comment by rajarshimaitra** [comment]
I haven't fully grasped on the down side of not having mutually exclusive features.. Is that a very big problem? Many things especially like DB might make more sense to be mutually exclusive I feel?

**Comment by notmandatory** [comment]
Not having [mutually exclusive features](https://doc.rust-lang.org/cargo/reference/features.html#mutually-exclusive-features) is recommended in the Cargo book but is probably more of an issue for libs than end bins like this project. But even here I think it would be useful to be able to enable all features and use them all without having to rebuild to enable/disable the ones I want to test with.
