### ISSUE TITLE
Update instructions to install the `repl`

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk-cli#7]
I guess we should change the instructions on bitcoindevkit.org to install the repl from the other repo - or even better as soon as we publish `bdk-cli` to crates.io we could just switch to using that by default instead of git.

_Originally posted by @afilini in https://github.com/bitcoindevkit/bdk/issues/248#issuecomment-754691372_

**Comment by notmandatory** [comment]
Good point I'll work on it.

**Comment by notmandatory** [comment]
closed by https://github.com/bitcoindevkit/bitcoindevkit.org/pull/19
