### ISSUE TITLE
Wrong help message for repl command

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-cli#70]
The `repl` command currently displays `Proxy Server options` as its short help message.

![repl-help](https://user-images.githubusercontent.com/39974688/154311764-1a930de6-829a-4337-aaaf-bfab1ede1efc.png)

It should probably say something like `Enter read-eval-print loop workflow` or something similar.

**Comment by notmandatory** [comment]
Should be fixed with #69 😄

**Comment by thunderbiscuit** [comment]
Awesome!
