### ISSUE TITLE
Help printout is broken on repl

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-cli#78]
The help printout works well on `v0.3.0`:
<img width="1490" alt="v0 3 0" src="https://user-images.githubusercontent.com/39974688/157703296-2716a1ed-d9b9-4aeb-90d8-008670fef10f.png">

<br/>

But is broken on `v0.3.1`:
<img width="1506" alt="v0 3 1" src="https://user-images.githubusercontent.com/39974688/157703399-9eb7d7cb-cd8f-46ea-be49-a9eda2fb2c88.png">

**Comment by thunderbiscuit** [comment]
Actually it's not the printout that's broken it's the whole `help` command, which exits the repl completely.

**Comment by rajarshimaitra** [comment]
This is so weird. Its happening on current master too.. The entire help output is being passed into a `Generic` error type somehow.. But this is something internal to `structop`. Because we don't handle the help command ourselves.. I will dig more..

**Comment by notmandatory** [comment]
This is fixed by #82.
