### ISSUE TITLE
Allow Sqlite DB

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk-cli#83]
Currently `bdk-cli` only uses sled database. But BDK now supports sqlite too. This can be extended to bdk-cli using a `sqlite` feature flag.

Having Sqlite DB in wallet database can be useful for lib users in many situations.

**Comment by notmandatory** [comment]
I saw this and thought, good idea! Then I remembered I started it with PR #71, but need to get it rebased and cleaned up. But if anyone else is interested and wants to help with review and testing that would be great!

**Comment by rajarshimaitra** [comment]
Yes I saw that one, and it fixes this.. Last I remember it was pending for additive feature capability.. But then again doesn't it make sense here to have wallet with only one db feature at a time?? What would it mean to have both `sled` and `sqlite` enabled?? 

In case we are not going towards that additive thing, then I think #71 works perfect.. I will review it again when its ready..

**Comment by notmandatory** [comment]
Thanks, I'm going to merge #71 without the additive stuff for now.
