### ISSUE TITLE
Show valid options in help where possible

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-cli#88]
Anywhere where there are only a limited enum set of options, such as with the network option, we should show in the help what those options are. This is done with the `possible_values` structopt feature, see example in Compile command: 

```rust
Compile {
        /// Sets the spending policy to compile
        #[structopt(name = "POLICY", required = true, index = 1)]
        policy: String,
        /// Sets the script type used to embed the compiled policy
        #[structopt(name = "TYPE", short = "t", long = "type", default_value = "wsh", possible_values = &["sh","wsh", "sh-wsh"])]
        script_type: String,
    },
```

**Comment by oleonardolima** [comment]
@notmandatory I'm taking a look at this one, it's still up for takers?

**Comment by rajarshimaitra** [comment]
@oleonardolima you can try to apply them on top of #104 if you are still up for it. That will be the final version of the crate after the big changes.. So you don't have to make duplicate works..

**Comment by oleonardolima** [comment]
@rajarshimaitra great! thanks for the suggestion, I'll work on top of it.

**Comment by oleonardolima** [comment]
@notmandatory @rajarshimaitra I've gone through all the available commands in the current state of #104 as Raj suggested.

But I didn't find any other than the `network` one that could use the `possible_values`,  I'm not sure if I missed something 🤔 

@rajarshimaitra as it's on top of #104 I'm going to open a [PR](https://github.com/rajarshimaitra/bdk-cli/pull/2) to [your branch](https://github.com/rajarshimaitra/bdk-cli/tree/docs), wdyt ?

**Comment by notmandatory** [comment]
Hi, sorry for the delay in getting to this, it's Ok if only network needs to be changed. You should be able to make your PR against the `master` bdk-cli branch so I can put it on our roadmap for the next release, but after raj's PRs are in you'll need to rebase your PR for this issue to pick up his changes before we can merge it. Thanks!

**Comment by oleonardolima** [comment]
@notmandatory no problem 😁 , actually Raj got the commit https://github.com/bitcoindevkit/bdk-cli/pull/104/commits/2999a3dc8a0e59b62b4de5308f80110d77dee5eb with the changes into the branch for #104.
